// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC34bKAJi6L2BsrbD_Bh3dtPXpysta2d7E',
    appId: '1:184238601360:web:bcace51d81ffdde3ca1415',
    messagingSenderId: '184238601360',
    projectId: 'stock-80736',
    authDomain: 'stock-80736.firebaseapp.com',
    storageBucket: 'stock-80736.firebasestorage.app',
    measurementId: 'G-FN9D45S5Z8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD69h7KflEiwidf2I32F25tsVGqybTcTBA',
    appId: '1:184238601360:android:54f639790da6e8c3ca1415',
    messagingSenderId: '184238601360',
    projectId: 'stock-80736',
    storageBucket: 'stock-80736.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDpXF8lSBEoIwcIOftx6j5qnHn8i0QFxIM',
    appId: '1:184238601360:ios:74da7aeaecaf0ccfca1415',
    messagingSenderId: '184238601360',
    projectId: 'stock-80736',
    storageBucket: 'stock-80736.firebasestorage.app',
    iosBundleId: 'com.example.stockInv',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDpXF8lSBEoIwcIOftx6j5qnHn8i0QFxIM',
    appId: '1:184238601360:ios:74da7aeaecaf0ccfca1415',
    messagingSenderId: '184238601360',
    projectId: 'stock-80736',
    storageBucket: 'stock-80736.firebasestorage.app',
    iosBundleId: 'com.example.stockInv',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC34bKAJi6L2BsrbD_Bh3dtPXpysta2d7E',
    appId: '1:184238601360:web:8ce808707343f7a4ca1415',
    messagingSenderId: '184238601360',
    projectId: 'stock-80736',
    authDomain: 'stock-80736.firebaseapp.com',
    storageBucket: 'stock-80736.firebasestorage.app',
    measurementId: 'G-64XSSJ35J8',
  );

}